services:
  - type: web
    name: fast-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fast-api-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0

databases:
  - name: fast-api-db
    databaseName: fastapi_db
    user: fastapi_user
